# docker-compose.yml

version: '3.7'
services:
  postgres:
    image: postgres:13.3-alpine
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - '127.0.0.1:${DB_PORT}:5432'
    volumes:
      - ${POSTGRES_DB_PERSIST_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
